title: Tempo
description: CCS Research Pipeline for Whole-Genome and Whole-Exome Sequencing
themeConfig:
  logo: /allegro.jpg
  sidebar:
    - "/"
    - title: Setup
      collapsable: false
      children:
        - "/installation"
        - "/juno-setup"
        - "/aws-setup"
    - title: Usage
      collapsable: false
      children:
        - "/running-the-pipeline"
        - "/nextflow-basics"
        - "/working-with-containers"
    - "/outputs"
    - "/bioinformatic-components"
    - "/reference-resources"
    - "/variant-annotation-and-filtering"
    - title: Help and Other Resources 
      collapsable: false
      children:
        - "/troubleshooting"
        - "/aws-glossary"
        - "/contributing-to-tempo"
        - "/acknowledgements"
  repo: mskcc/vaporware
  docsBranch: 'develop'
plugins:
- - vuepress-plugin-medium-zoom
  - selector: "#diagram"
    delay: 1000
    options:
      margin: 24
      scrollOffset: 0
